Refactor and add tests
danyal002/cmd-stack pull request #24
Opened 2024-10-08 00:53 UTC by dylan-p-wong

Refactor logic layer and data layer to allow use of temp dirs for testing.

Add tests for commands in logic layer.

2024-10-18 15:39 UTC, danyal002 requested changes

2024-10-18 15:39 UTC, danyal002 commented on logic/src/lib.rs
> +}
This is not the best way to do this. We call or talk about it in person if you need more details. Essentially, we want an interface for the dal and abstract the SQLite stuff away. So, you want to implement a new interface called something like `Storage` or `StorageDal`. This will have some methods to `initialize()`, `add()`, `update()`, `delete()`, `get()` etc. These interface methods should take in objects like `InternalCommand` or `Command` or something like that. The database should be completely abstracted away. Once a command is read, these interface methods should be called. 

You will most likely need a conversion method to convert from `InternalCommand` to `Command` or vice-versa. Rust has great support for writing these [conversion methods.](https://doc.rust-lang.org/rust-by-example/conversion/from_into.html). 

In order to instrument our program for logs, we need to work on setting up the error handling right now. Once this interface is created, we need low-level, intermediate and user-level errors. This is easy to do with `this error`. Refer to `data/src/dal/sqlite.rs` to see how the conversion is happening.

2024-10-18 15:39 UTC, danyal002 commented on logic/src/param.rs
> +        };
General comment for the `db_connection`. I think once the interface is implemented, we need to make a design decision on getting database connections. This important to think about because if our frontend is running at all times, we'll probably have a connection open on startup. We'll need to pool those connections. Let's talk in person.

2024-10-18 18:55 UTC, dylan-p-wong commented on logic/src/lib.rs
> +}
Changed ```SqliteDal``` to ```Box<dyn Dal<Row = SqliteRow, DB = Sqlite>>```. I do not think there is a simple way to abstract SqlLite away completely if we are using transactions since a lot of the DAL methods contain ```async fn delete_command(
        &self,
        command_id: i64,
        tx: Option<&mut Transaction<'_, Self::DB>>``` where DB is some sqlx type.

2024-10-19 15:21 UTC, Pop0097 approved these changes
Really great work, Dylan. I just had a few nits for our log messages.

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/command/search_command.rs
> +        );
```suggestion
            target: "Search Cmd", "Failed to initialize logic: {:?}",
            logic.err()
        );
```

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/command/add_command.rs
> +        error!(target: "Add Cmd", "Error adding command: {:?}", logic.err());
```suggestion
        error!(target: "Add Cmd", "Failed to initialize logic: {:?}", logic.err());
```

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/command/delete_command.rs
> +        error!(target: "Delete Cmd", "Failed to delete command: {:?}", logic.err());
```suggestion
        error!(target: "Delete Cmd", "Failed to initialize logic: {:?}", logic.err());
```

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/command/search_utils.rs
> +                logic::DefaultLogicError::DbConnection(DatabaseConnectionError::InitDBConnection),
**NIT:** We may want a different error message for initializing the logic instead of returning the `InitDbConnetion` error.

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/command/update_command.rs
> +        error!(target: "Update Cmd", "Failed to update command: {:?}", logic.err());
```suggestion
        error!(target: "Update Cmd", "Failed to initialize logic: {:?}", logic.err());
```

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/import_export.rs
> +        error!(target: "Export Cmd", "Failed to export command: {:?}", logic.err());
```suggestion
        error!(target: "Export Cmd", "Failed to initialize logic: {:?}", logic.err());
```

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/import_export.rs
> +        error!(target: "Import Cmd", "Failed to import command: {:?}", logic.err());
```suggestion
        error!(target: "Import Cmd", "Failed to initialize logic: {:?}", logic.err());
```

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/param/add_param.rs
> +        error!(target: "Add Param Cmd", "Error adding parameters: {:?}", logic.err());
```suggestion
        error!(target: "Add Param Cmd", "Failed to initialize logic: {:?}", logic.err());
```

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/param/delete_param.rs
> +        error!(target: "Param Delete Cmd", "Error deleting parameter: {:?}", logic.err());
```suggestion
        error!(target: "Param Delete Cmd", "Failed to initialize logic: {:?}", logic.err());
```

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/param/mod.rs
> +        error!(target: "Param Cmd", "Error getting parameters: {:?}", logic.err());
```suggestion
        error!(target: "Param Cmd", "Failed to initialize logic: {:?}", logic.err());
```

2024-10-19 15:21 UTC, Pop0097 commented on cli/src/param/update_param.rs
> +        error!(target: "Param Update Cmd", "Error updating parameter: {:?}", logic.err());
```suggestion
        error!(target: "Param Update Cmd", "Failed to initialize logic: {:?}", logic.err());
```

2024-10-19 15:21 UTC, Pop0097 commented on logic/src/param.rs
> +        };
I don't think we need to worry about this as Sqlite should provide thread safety automatically: https://sqlite.org/faq.html#q5

2024-10-19 15:28 UTC, Pop0097 commented on logic/src/lib.rs
> +}
I think the latest changes Dylan pushed up are more than sufficient. Since we don't plan on building out a backend anymore, we most likely will not use a different datastore than sqlite3. I'd say it's better to put our time towards building out the GUI and making the CLI more usable.

2024-10-19 16:03 UTC, danyal002 approved these changes

2024-10-19 16:03 UTC, danyal002 commented on logic/src/lib.rs
>      NoneAfterInit,
Nit: this isn't your code, but a good time to fix this. The enum already tells me what the error is about, so the description isn't required or it can say something else like "Could not initialize database". When we instrument our application, the logs will make much more sense because the error message will immediately tell you the problem, and the stack trace will immediately tell you why it happened because of the enums.

2024-10-19 21:50 UTC, dylan-p-wong commented on cli/src/command/search_utils.rs
> +                logic::DefaultLogicError::DbConnection(DatabaseConnectionError::InitDBConnection),
Changed to ```return Err(GetSelectedItemFromUserError::GetCommands(e));```

2024-10-19 21:53 UTC, dylan-p-wong commented on logic/src/lib.rs
>      NoneAfterInit,
Not addressing in this PR.

2024-10-19 21:54 UTC, merged