Add basic GUI styling
danyal002/cmd-stack pull request #26
Opened 2024-11-03 15:19 UTC by dylan-p-wong

<img width="1287" alt="image" src="https://github.com/user-attachments/assets/e504a88a-0a74-414a-9fc0-5b6fa84e20b7">

How to use shadcn https://ui.shadcn.com/docs/components/accordion.

For example, if we want to add an accordion.

```
npx shadcn@latest add accordion
```

This will then create a new file in the ui/components directory. It is not a library.

2024-11-03 15:20 UTC, dylan-p-wong commented on ui/src-tauri/Cargo.toml
> +rustls-pemfile = { version = "2.2.0" }
Was having issues running ```yarn tauri dev``` so had to add this.

2024-11-03 15:22 UTC, dylan-p-wong commented on ui/src-tauri/src/lib.rs
> +#[derive(Debug, Clone, Serialize, Deserialize)]
Had to add this structure to translate the full command to the GUI. We can figure out a better solution for this later I just want to get the main frontend structure in main.

2024-11-03 16:04 UTC, danyal002 requested changes
I'll leave the frontend review for @Uzair5162

2024-11-03 16:04 UTC, danyal002 commented on ui/src-tauri/src/lib.rs
> +    Ok(commands)
Could you implement a `From` trait here instead of mapping every property? https://doc.rust-lang.org/rust-by-example/conversion/from_into.html

2024-11-07 21:21 UTC, Uzair5162 requested changes

2024-11-07 21:21 UTC, Uzair5162 commented on ui/package-lock.json
We're using yarn and have a `yarn.lock`, so we shouldn't have a `package-lock.json`. We should use yarn equivalents for any npm command that might've created this during setup.

2024-11-07 22:09 UTC, dylan-p-wong commented on ui/src-tauri/src/lib.rs
> +    Ok(commands)
Done.

2024-11-07 22:09 UTC, dylan-p-wong commented on ui/package-lock.json
Done good catch.

2024-11-07 23:22 UTC, Uzair5162 approved these changes

2024-11-08 06:13 UTC, danyal002 commented on ui/src-tauri/src/lib.rs
> +    let commands: Vec<DisplayCommand> = commands.iter().map(|c| DisplayCommand::from(c)).collect();
minor minor nit: the rusty way of doing this is to `.map(|c| c.into()).collect();` (I think) because implementing `From` gives you the `Into` for free.  If you do `.map(|c| c.into()).collect();`, I have a feeling that cargo is going to tell you to do `.map(Into::into).collect();` instead which is even more idiomatic.

2024-11-08 06:14 UTC, danyal002 approved these changes

2024-11-08 15:35 UTC, merged