refactor: Update DAL to use SQLite3 instead of Badger
danyal002/cmd-stack pull request #3
Opened 2024-05-14 14:00 UTC by Pop0097

2024-05-14 18:09 UTC, danyal002 requested changes

2024-05-14 18:09 UTC, danyal002 commented on cli/cmd/add.go
> +			alias = cmdText
I don't think we need the alias anymore because we can use FTS (full text search) on SQL. It can search through entire objects and rows for us. We need an experiment for this and see how it works.

2024-05-14 18:09 UTC, danyal002 commented on cli/cmd/add.go
> +		err = data_access_layer.AddCommand(alias, cmdText, tags, note, 0)
Did you hardcode this on purpose to come back and auto increment the primary key?

2024-05-14 18:09 UTC, danyal002 commented on cli/cmd/list.go
> +	Long:  `missing_docs`,
I would do what we talked about yesterday. The main command would be to list all commands with a flag like `-r` to list recently used. You can also add `-l` for length to limit the number of rows. However, this last part can be done in another PR.

2024-05-14 18:09 UTC, danyal002 commented on cli/dal/command.go
> +	UserId   *uint64
I'd remove this field. We don't need it right now.

2024-05-14 18:09 UTC, danyal002 commented on cli/dal/command.go
> +func PrintCommands(commands []Command) {
can this be a method too?

EDIT: I think this will get deleted in future iterations, so it doesn't matter atm.

2024-05-14 18:09 UTC, danyal002 commented on cli/dal/dal.go
> +	stmt, err := dal.db.Prepare("SELECT * FROM command WHERE command LIKE ?")
I wonder if there's an option we need to turn on for FTS because this might be too slow. No need to fix this now.

2024-05-14 18:09 UTC, danyal002 commented on cli/dal/parameter.go
> +	CommandId    *uint64
what's the difference between these two?

2024-05-14 18:18 UTC, Pop0097 commented on cli/cmd/list.go
> +	Long:  `missing_docs`,
I plan on implementing this feature in another PR

2024-05-14 18:19 UTC, Pop0097 commented on cli/dal/parameter.go
> +	CommandId    *uint64
Id is the unique identifier of the Parameter row in the `parameter` table. CommandId is a foreign key reference to the command that the parameter was created for. I can add a comment for that.

2024-05-14 18:20 UTC, Pop0097 commented on cli/cmd/add.go
> +			alias = cmdText
We will most likely want the alias when we build the GUI

2024-05-14 18:21 UTC, Pop0097 commented on cli/cmd/add.go
> +		err = data_access_layer.AddCommand(alias, cmdText, tags, note, 0)
The `0` is the user id. Since we don't have the concept of a user right now, I will remove it.

2024-05-14 18:53 UTC, Pop0097 commented on cli/dal/dal.go
> +	stmt, err := dal.db.Prepare("SELECT * FROM command WHERE command LIKE ?")
I think I will save FTS for a separate PR since it is not essential at the moment.

2024-05-15 05:45 UTC, danyal002 approved these changes

2024-05-15 13:44 UTC, merged