Delete commands by ID
danyal002/cmd-stack pull request #5
Opened 2024-05-16 22:19 UTC by Pop0097

`go run main.go delete -i <ID>`

The user is presented with a success/error statement if:
1. The command does not exist in the database
2. The deletion was successful

2024-05-17 05:04 UTC, danyal002 requested changes

2024-05-17 05:04 UTC, danyal002 commented on cli/cmd/delete.go
> +			log.Fatal(err)
I would be consistent like your other PR and have a more descriptive error message.

2024-05-17 05:04 UTC, danyal002 commented on cli/cmd/delete.go
> +		if errors.Is(err, dal.MissingCommandError) {
I like this way of error handling. We did the same in Rust at Haven. I would go back and either modify your other PR to do the same or do it in another PR.

It might be a good idea to separate logic from interfaces/error definitions into different files.

2024-05-17 05:04 UTC, danyal002 commented on cli/dal/dal.go
> +		log.Fatal(err)
Same comment about descriptive error message here.

2024-05-17 05:04 UTC, danyal002 commented on cli/dal/dal.go
> +		log.Fatal(err)
here as well.

2024-05-17 05:04 UTC, danyal002 commented on cli/dal/dal.go
> +	}
You don’t need to do this. I think SQL will _not_ return an error message if you delete something that doesn't exist. We can do the same.

2024-05-17 05:06 UTC, danyal002 commented
> The user is presented with a success/error statement if:
> 2. The deletion was successful

I don't think you need to display anything if the deletion was successful regardless of whether the command exists at the time of deletion or not. Most CLI tools just exit once you run a deletion command.

2024-05-19 18:59 UTC, Pop0097 commented on cli/dal/dal.go
> +	}
I tested it and it doesn't

2024-05-26 02:14 UTC, danyal002 approved these changes

2024-05-26 14:01 UTC, merged