feat: allow users to search for commands
danyal002/cmd-stack pull request #6
Opened 2024-05-26 16:28 UTC by Pop0097

This feature allows users the ability to search for commands using command line arguments. 

- `-a` for alias
- `-t` for tag
- `-c` for command

We search and filter in the following order
1. Tag
2. Command
3. Alias

Once the user selects a command, it is added to their clipboard and the last used property of the command is updated in the database. 

https://github.com/danyal002/cmd-stack/assets/52176616/90475bd1-cd32-4128-a732-92aaa024e6f2

2024-05-26 19:59 UTC, danyal002 requested changes

2024-05-26 19:59 UTC, danyal002 commented on cli/cmd/delete.go
> +		defer dataAccessLayer.CloseDataAccessLayer()
We should decide on a variable naming convention and stick to it. If we're going to use camel case, then we should change it everywhere in future PRs.

2024-05-26 19:59 UTC, danyal002 commented on cli/cmd/search.go
> +		return "", "", "", "", err
Hmm, I don't like this. This introduces more edge cases. We should either have a `nil` returned or an actual value. What do you think?

(This is coming from me programming in Rust and getting annihilated for doing the above in my PRs)

2024-05-26 19:59 UTC, danyal002 commented on cli/cmd/search.go
> +func searchArgsWizard(cur_tag string, cur_command string, cur_alias string) (string, string, string, string, error) {
why the `cur_` prefix?

2024-05-26 19:59 UTC, danyal002 commented on cli/cmd/search.go
> +	return tag, command, alias, printOption, nil
You don't have to do this in this PR, but this should be a results object, something like `SearchResult`.

2024-05-26 19:59 UTC, danyal002 commented on cli/cmd/search.go
> +	command, _ := cmd.Flags().GetString("command")
Imo, the "command" or `-c` should be the default argument for the search command e.g. `cmdstack search "some command" -t ... -n ...` and so on.

2024-05-26 19:59 UTC, danyal002 commented on cli/cmd/search.go
> +	// If no arguments are provided, we will present the user with a form
I think there's a better way to do this than what's below, but I can't remember off the top of my head. I remember reading somewhere that you can autogenerate this part using Cobra.

2024-05-26 19:59 UTC, danyal002 commented on cli/cmd/search.go
> +		commands = dal.FilterCommandsByCommand(commands, command)
Confusing name. A better name would be `FilterCommandsByCommandText` or `FilterCommandsByCommandContent`.

2024-05-26 19:59 UTC, danyal002 commented on cli/cmd/search.go
> +		Label: "Select Command (" + dal.GetPrintedValues(printOption) + ")",
I'd remove the "Select Command" prefix. The little triangle on the left side of every command in the list is enough to know what the user is doing. It is also less cognitive load.

2024-05-26 19:59 UTC, danyal002 commented on cli/dal/command.go
> +	return alias + " | " + command + " | " + tags + " | " + note
Hmm, whilst this is fine for now, this will quickly become a maintenance issue because we'll be reusing it everywhere. I would suggest searching for a library that can take care of this for us. I'm sure one exists.

In Rust, we used something called `Validator` which would use attributes on each struct property to validate a struct every time it was created.

2024-05-26 19:59 UTC, danyal002 commented on cli/dal/dal.go
> +		log.Fatal("SearchByCommand: Failed to perform query:", err)
nit: `Failed to execute query:`.

2024-05-26 19:59 UTC, danyal002 commented on cli/dal/dal.go
So, one big overarching comment I have is that I don't agree with your approach for search and filtering. A database is much better equipped to handle that for us. We're reinventing the wheel here. The way I would do this is by creating a `SearchFilters` object. You would then pass that to the `dal` `search` method and form your query using the filters. This is where `Squirrel` can help. You would validated the filters object there and return an error if the filters are invalid. Execute the query and create a `SearchResult` object to return.

2024-05-27 20:20 UTC, Pop0097 commented on cli/cmd/search.go
> +		Label: "Select Command (" + dal.GetPrintedValues(printOption) + ")",
I agree, however with the way that the UI is generated by the library you need a prompt otherwise a `:` just appears.

2024-06-01 16:59 UTC, Pop0097 commented on cli/cmd/search.go
> +	// If no arguments are provided, we will present the user with a form
Can you? I had to use an external library for this

2024-06-01 17:34 UTC, Pop0097 commented on cli/dal/command.go
> +	return alias + " | " + command + " | " + tags + " | " + note
Will do in future PR

2024-06-01 17:35 UTC, Pop0097 commented on cli/cmd/search.go
> +	command, _ := cmd.Flags().GetString("command")
Can address in future PR

2024-06-01 17:35 UTC, Pop0097 commented on cli/cmd/search.go
> +func searchArgsWizard(cur_tag string, cur_command string, cur_alias string) (string, string, string, string, error) {
Will remove

2024-06-01 17:35 UTC, Pop0097 commented on cli/cmd/search.go
> +		return "", "", "", "", err
This is a good catch, thanks for the suggestion!

2024-06-01 17:35 UTC, Pop0097 commented on cli/cmd/delete.go
> +		defer dataAccessLayer.CloseDataAccessLayer()
camel case

2024-06-02 23:03 UTC, danyal002 reviewed
Could you move the `example_commands.txt` file to a separate `test_data` directory please?

2024-06-02 23:03 UTC, danyal002 commented on cli/cmd/list.go
> +			log.Fatal("Search Cmd: Invalid print argument")
Nit: could this be better named? I'm not sure what the difference between `resultLimit` and `printLimit` is.

2024-06-02 23:03 UTC, danyal002 commented on cli/cmd/search.go
> +	searchCmd.Flags().IntP("limit", "l", 5, "Limit the number of commands to display before scrolling (defaults to 10)")
We should talk about setting up a config file for all these settings.

2024-06-02 23:03 UTC, danyal002 commented on cli/cmd/search.go
> +func extractAndValidateArgs(cmd *cobra.Command) (*dal.SearchFilters, *string, *int, error) {
This would be better as a method I think, unless you plan on using it without a `Command`.

2024-06-07 13:38 UTC, Pop0097 commented on cli/cmd/search.go
> +func extractAndValidateArgs(cmd *cobra.Command) (*dal.SearchFilters, *string, *int, error) {
Do you mean a method of the DAL?

2024-06-11 04:38 UTC, danyal002 commented on cli/cmd/search.go
> +func extractAndValidateArgs(cmd *cobra.Command) (*dal.SearchFilters, *string, *int, error) {
the `Command` object as it's always called on a `Command`.

2024-06-11 04:39 UTC, danyal002 approved these changes
Approving with one comment

2024-06-11 12:52 UTC, merged